# Generated by Django 4.0.4 on 2022-04-14 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('computerApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personnel',
            fields=[
                ('num_secu', models.CharField(editable=False, max_length=15, primary_key=True, serialize=False)),
                ('Nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=20)),
            ],
        ),
        migrations.AlterField(
            model_name='machine',
            name='nom',
            field=models.CharField(max_length=200),
        ),
    ]
